description.html

There is a typo in the description of the plugin. I've corrected it.

Fix typo in the description

---

build.gradle
change-notes.html
description.html
src/main/java/org/mapstruct/intellij/expression/JavaExpressionInjector.java
src/test/java/org/mapstruct/intellij/expression/JavaExpressionInjectionTest.java
src/test/java/org/mapstruct/intellij/testutil/TestUtils.java
testData/expression/dto/NumberWrapper.java
testData/expression/dto/Utils.java
testData/expression/dto/Wrapper.java

primary enhancements being around generics.

Improve Java expression injector both for better code completion and for more useable inspections,

---

src/main/java/org/mapstruct/intellij/inspection/UnmappedTargetPropertiesInspection.java

Currently there is no need to check for `null` and then return `null`. So I removed the redundant check and directly returned the value.

remove redundant if from UnmappedTargetPropertiesInspection

---

src/main/java/org/mapstruct/intellij/inspection/UnmappedTargetPropertiesInspection.java
src/main/java/org/mapstruct/intellij/util/MapstructAnnotationUtils.java
src/test/java/org/mapstruct/intellij/inspection/BaseInspectionTest.java
src/test/java/org/mapstruct/intellij/inspection/UnmappedTargetPropertiesInspectionCaretAfterQuickfixTest.java
testData/inspection/UnmappedTargetPropertiesJdk8.java
testData/inspection/UnmappedTargetPropertiesJdk8_after.java

This PR fixes #28.
The test handles the case with and without surrounding `@Mappings({...})` annotation.

Set caret position to empty source attribute after quick fix

---

src/main/java/org/mapstruct/intellij/inspection/UnmappedTargetPropertiesInspection.java
src/test/java/org/mapstruct/intellij/inspection/UnmappedTargetPropertiesSubObjectMappingTest.java
testData/inspection/UnmappedTargetPropertiesData.java
testData/inspection/UnmappedTargetPropertiesSubObjectMapping.java

Currently the plugin gives a warning if an field is mapped with `@Mapping` where the target contains a dot.
This fixes the issue, by splitting the target on the dot and only removing the first part from `allTargetProperties`.
I also wrote a small test covering this issue.

fix wrong unmapped target warning with Mapping annotation

---

src/main/java/org/mapstruct/intellij/inspection/UnmappedTargetPropertiesInspection.java
src/main/java/org/mapstruct/intellij/util/InheritConfigurationUtils.java
src/main/java/org/mapstruct/intellij/util/MapstructUtil.java
src/main/java/org/mapstruct/intellij/util/TargetUtils.java
src/test/java/org/mapstruct/intellij/inspection/InheritConfigurationInspectionTest.java
testData/inspection/InheritConfigurationByInheritanceMapper.java
testData/inspection/InheritConfigurationByMapperConfigMapper.java
testData/inspection/InheritConfigurationByNameMapper.java
testData/inspection/InheritConfigurationBySuperMapperMapper.java
testData/inspection/InheritConfigurationInSameClassMapper.java
testData/inspection/InheritConfigurationInSameClassOfUpdateMethodMapper.java
testData/inspection/InheritConfigurationInSameClassWithContextMapper.java

I could narrow it down to the following use cases:
* `@InheritConfiguration` from a method in...
* the same mapper (local reference)
* super mapper
* by name 
* a referenced `@MapperConfig`
* the same mapper (local reference) but with another type that can be inherited from (e.g. inheritance like `Person <- NaturalPerson`)
For all these I have provided a test case.
I am using an approach with two steps:
* search for all possible methods in the scope where `@InheritConfiguration` might be possible
* find a single method that can be inherited from - as you suggested: when there is more than one candidate, nothing will be returned
Fixes #65

#65 support inherit configuration

---

src/main/java/org/mapstruct/intellij/util/MapstructAnnotationUtils.java
src/test/java/org/mapstruct/intellij/inspection/UnmappedTargetPropertiesWithMetaAnnotationInspectionTest.java
testData/inspection/MetaMappingMetaAnnotationChainTarget.java
testData/inspection/MetaMappingMetaAnnotationChained.java
testData/inspection/UnmappedTargetPropertiesWithMetaAnnotationAndMapping.java
testData/inspection/UnmappedTargetPropertiesWithMetaAnnotationChained.java

This PR is about #129.
Mapping composition (or meta annotations) were already tacklet with the following commit (target version 1.2.1): https://github.com/mapstruct/mapstruct-idea/commit/35f171224af8267163f33edcedb92b01d14a3bbc
However, the used utility method `com.intellij.codeInsight.MetaAnnotationUtil#findMetaAnnotations` returns only **a single** (more precise: the first) `@Mapping` annotation. Therefore this did not work as expected (but already worked with the simple test named `UnmappedTargetPropertiesWithMetaAnnotationInspectionTest`.
I implemented an own recursive method to find `@Mapping` annotations and provided a test case with an infinitve chained meta-annotation.
I also added a test with combined `@Mapping` and meta-annotation on the same mapping method. The current …

#129 improve support of mapping composition 

---

src/main/java/org/mapstruct/intellij/codeinsight/completion/ComponentModelCompletionContributor.java

Since Java 9 `List.of` can be used to declare unmodifiable list. I also added the missing `@NotNull` annotation for `ProcessingContext context`.

use List.of for unmodifiableList

---

src/main/java/org/mapstruct/intellij/util/MapstructAnnotationUtils.java
src/main/java/org/mapstruct/intellij/util/TargetUtils.java

I used `findDeclaredAttributeValue` because we are only interested in type `PsiAnnotationMemberValue` and function `findDeclaredAttributeValue`  returns it directly. This way we can avoid a few unnecessary null checks.
Also, I have removed the convert from stream to list and back again, in the function `findReferencedMappers`.
Lastly, I added the missing null/notNull-annotations.

use findDeclaredAttributeValue to get PsiAnnotationMemberValue directly

---

build.gradle

I upgrade `commons-text` to 1.10.0 to prevent any use of [CVE-2022-4288](https://devhub.checkmarx.com/cve-details/CVE-2022-42889/?utm_source=jetbrains&utm_medium=referral&utm_campaign=idea&utm_term=maven). 
Currently this dependency is only used in tests, so the main plugin is not effected, but still it should be upgraded. 
The effected `StringSubstitutor`  is used in tests.

upgrade commons-text

---

src/main/java/org/mapstruct/intellij/codeinsight/references/MapstructTargetReference.java
src/main/java/org/mapstruct/intellij/expression/JavaExpressionInjector.java
src/test/java/org/mapstruct/intellij/bugs/_110/MethodeWithNoParametersTest.java
testData/bugs/_110/MapDefaultExpression.java
testData/bugs/_110/MapExpression.java
testData/bugs/_110/TargetCompletion.java
testData/bugs/_110/TargetNoPropertyMethode.java
testData/bugs/_110/TargetNoPropertyMethods.java

I was able to reproduce #110. The error occurs when the target method has no parameters and the IDE tries to evaluate the expression. I found that the same problem results in a crash if you try to complete an sub-method of such an target.
I provided testcases for both problems and the fixes.
Fixes #110

fix IndexOutOfBoundsException for target methods without parameter

---

README.md

In #131 I forgot to change the description in the README for `unmappedTargetPolicy`. Now it matches the description in `description.html`.

correct README for unmappedTargetPolicy

---

src/main/java/org/mapstruct/intellij/settings/ProjectSettingsPage.java

The return value of `isModified` can be directly returned.

inline return value of isModified

---

src/main/java/org/mapstruct/intellij/codeinsight/references/MapstructSourceReference.java
src/main/java/org/mapstruct/intellij/codeinsight/references/MapstructTargetReference.java
src/test/java/org/mapstruct/intellij/MapstructCompletionTestCase.java
testData/mapping/NestedSecondLevelAutoCompleteSourcePublicProperty.java
testData/mapping/NestedSecondLevelAutoCompleteTargetPublicProperty.java

I wanted to reproduce another bug and stumbled accross the lack of support for auto-completion of nested properties when they are public fields.
I provided a test case and fixed it although this is possibly an edge case.

Fix auto-completion for nested public fields

---

src/main/java/org/mapstruct/intellij/util/TargetUtils.java
src/test/java/org/mapstruct/intellij/inspection/UnmappedCollectionGetterPropertiesInspectionTest.java
testData/inspection/UnmappedCollectionGetterProperties.java
testData/inspection/UnmappedCollectionGetterPropertiesData.java

Currently, mapstruct supports getter targets where the return-type is instance of a collection.

add support for collection targets from getter

---

src/main/java/org/mapstruct/intellij/expression/JavaExpressionInjector.java
src/test/java/org/mapstruct/intellij/expression/JavaExpressionInjectionTest.java

Add "conditionExpression" missing support

Support java expressions in `Mapping#conditionExpression`

---

.github/workflows/main.yml
build.gradle
gradle.properties

Adding `2023.2` (since EAP is already `2023.3.xxx`)
Also removed the pipelines for the oldest versions `2021.2` and `2021.3`.
The git history showed that there have never been more than 7 different IntelliJ versions.
@filiphr WDYT, should we still keep them?

Add IntelliJ 2023.2 and remove 2021.2, 2021.3

---

src/main/resources/META-INF/plugin.xml

Currently the plugin uses `com.intellij.codeInspection.DefaultAnnotationParamInspection.IgnoreAnnotationParamSupport` and overrides `com.intellij.openapi.options.UnnamedConfigurable`. Both are available since 212.4746.92. To prevent issue with older 212.* versions, I upgrade the required version to 213 (2021.3).

update since-build to 213

---

build.gradle

I upgrade the  Gradle IntelliJ Plugin to the latest version. It is recommended to use the latest version. The complete changelog can be found here [https://github.com/JetBrains/gradle-intellij-plugin/releases](https://github.com/JetBrains/gradle-intellij-plugin/releases)

update Gradle IntelliJ Plugin to 1.16.1

---

src/main/java/org/mapstruct/intellij/expression/JavaExpressionInjector.java

@filiphr I changed the implementation to match the [core](https://github.com/mapstruct/mapstruct/blob/fa857e9ff46b5bb3e5a6c2c8b1c56009944f5ef3/processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingOptions.java#L40)  implementation as you suggested in #164. The only difference is that idea needs the `\"` at the beginning and end of the string.

match Java expression core implementation

---

src/main/java/org/mapstruct/intellij/inspection/MappingAnnotationInspectionBase.java
src/main/java/org/mapstruct/intellij/inspection/MoreThanOneSourcePropertyDefinedInspection.java
src/main/java/org/mapstruct/intellij/inspection/TargetThisMappingNoSourcePropertyInspection.java
src/main/resources/META-INF/plugin.xml
src/main/resources/inspectionDescriptions/TargetThisMappingNoSourcePropertyInspection.html
src/main/resources/org/mapstruct/intellij/messages/MapStructBundle.properties
src/test/java/org/mapstruct/intellij/inspection/MoreThanOneSourcePropertyDefinedInspectionTest.java
src/test/java/org/mapstruct/intellij/inspection/TargetThisMappingNoSourcePropertyInspectionTest.java
testData/inspection/MoreThanOneSourceConstantAndSourceThisMapping.java
testData/inspection/MoreThanOneSourceConstantAndSourceThisMapping_after.java
testData/inspection/MoreThanOneSourceExpressionAndSourceThisMapping.java
testData/inspection/MoreThanOneSourceExpressionAndSourceThisMapping_after.java
testData/inspection/TargetThisMappingNoSourceProperty.java

As a followup of mapstruct/mapstruct#3540 I added an inspection to check if the target `.` is used without a source property. In addition I disabled the remove suggestion of the source property if the target is  `.` and the options to use constant or expression as default values.

Inspection for Mapping to target = "." without source

---

src/main/java/org/mapstruct/intellij/inspection/WrongUsageOfMappersFactoryInspection.java

@filiphr I found a working solution for #155 
I used the `SafeDeleteFix` to delete the instance unlike my solution in #176 it checks for usage.

Fix RemoveMappersFix by using SafeDeleteFix

---

src/main/java/org/mapstruct/intellij/util/MapstructUtil.java
src/test/java/org/mapstruct/intellij/inspection/UnmappedSuperBuilderTargetPropertiesInspectionTest.java
testData/inspection/UnmappedSuperBuilderTargetProperties.java
testData/inspection/UnmappedSuperBuilderTargetPropertiesData.java
testData/inspection/UnmappedSuperBuilderTargetProperties_after.java

I hope this change has no unwanted side effects. It checks whether a fluent setters return type also can be assigned to one of its super types to support classes like this:
```java
public static abstract class TargetBuilder<C extends Target, B extends TargetBuilder<C, B>> {
private String testName;
public B testName(String testName) {
this.testName = testName;
return self();
}
// ...
}
```
Fixes #159

#159 support fluent setters with super types (e.g. lomboks @SuperBuilder)

---

src/main/java/org/mapstruct/intellij/expression/JavaExpressionInjector.java
src/main/java/org/mapstruct/intellij/inspection/JavaExpressionUnnecessaryWhitespacesInspector.java
src/test/java/org/mapstruct/intellij/expression/JavaExpressionInjectionTest.java
src/test/java/org/mapstruct/intellij/inspection/JavaExpressionUnnecessaryWhitespacesInspectorTest.java
testData/inspection/JavaExpressionUnnecessaryWhitespacesTextBlock.java

I added support for Java text blocks for expression injection. The only change necessary to support this was to change `JAVA_EXPRESSION`  to accept one or three quotation marks.
In addition I disabled `JavaExpressionUnnecessaryWhitespacesInspector` if a text block is used.

Add support for java text-blocks for expression injection

---

src/main/java/org/mapstruct/intellij/inspection/WrongUsageOfMappersFactoryInspection.java
src/main/java/org/mapstruct/intellij/util/MapstructAnnotationUtils.java
src/test/java/org/mapstruct/intellij/bugs/_180/WrongUsageOfMappersFactoryFromConfigInspectionTest.java
testData/bugs/_180/WrongUsageOfMappersFactoryFromConfig.java
testData/bugs/_180/WrongUsageOfMappersFactoryFromConfig_after.java

I added support to read the `componentModel` from a `MapperConfig` for `WrongUsageOfMappersFactoryInspection` see #180 .
I only added the quickfix to remove `Mappers` usage. I think it is more intuitive to not write to other files for this. If we want to support this we must ensure that we could write to the `MapperConfig` (could be provided as a dependency for example).

Fix issue 180. WrongUsageOfMappersFactory componentModel from config

---

.github/workflows/main.yml

Added latest released version to build matrix

add idea 2024.1 to build matrix

---

build.gradle

As pointed out in #189 the jacoco report is currently not working. Idea SDK 2022.1+ needs a special configuration, see [https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-faq.html#jacoco-reports-0-coverage](https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-faq.html#jacoco-reports-0-coverage).

fix jacoco-reports-0-coverage

---

src/main/java/org/mapstruct/intellij/inspection/NoSourcePropertyDefinedInspection.java
src/test/java/org/mapstruct/intellij/bugs/_194/NoSourcePropertyDefinedSourcePropertyWithSameNameExistsInspectionTest.java
testData/bugs/_194/NoSourcePropertyDefinedSourcePropertyWithSameNameExists.java

I think I found the root cause of #194. As show in the example of #196 the plugin currently doesn't check if there exists a source property with the same name.
Fixes #194

fix issue 194 source property with same name exists

---

src/main/java/org/mapstruct/intellij/util/MapstructAnnotationUtils.java

Just a small refactoring. The two Strings are never `null`. No need to use `Objects.equals`

use String equals directly instead of Objects.equals

---

.github/workflows/main.yml
build.gradle
gradle.properties
src/main/java/org/mapstruct/intellij/codeinsight/references/MapstructBaseReference.java
src/main/java/org/mapstruct/intellij/codeinsight/references/MapstructSourceReference.java
src/main/java/org/mapstruct/intellij/codeinsight/references/MapstructTargetReference.java
src/main/java/org/mapstruct/intellij/expression/JavaExpressionInjector.java
src/main/java/org/mapstruct/intellij/inspection/FromMapMappingMapTypeInspection.java
src/main/java/org/mapstruct/intellij/inspection/JavaExpressionUnnecessaryWhitespacesInspector.java
src/main/java/org/mapstruct/intellij/inspection/MappingAnnotationInspectionBase.java
src/main/java/org/mapstruct/intellij/inspection/WrongUsageOfMappersFactoryInspection.java
src/main/java/org/mapstruct/intellij/util/MapstructAnnotationUtils.java
src/main/java/org/mapstruct/intellij/util/SourceUtils.java
src/main/java/org/mapstruct/intellij/util/TargetUtils.java
src/main/java/org/mapstruct/intellij/util/patterns/KtValueArgumentNamePattern.java
src/main/resources/META-INF/plugin.xml
src/test/java/org/mapstruct/intellij/ValueMappingCompletionTestCase.java
src/test/java/org/mapstruct/intellij/expression/JavaExpressionInjectionTest.java
src/test/java/org/mapstruct/intellij/inspection/UnmappedTargetPropertiesInspectionCaretAfterQuickfixTest.java

I removed support for idea 2022.1. This was the last version using Java 11. In addition I also used remove the new migration aids. Where possible I used enhanced switches, text blocks and the new instanceof casts.

upgrade to Java 17

---

src/main/java/org/mapstruct/intellij/util/patterns/KtAnnotationEntryPattern.java
src/main/resources/META-INF/plugin.xml
src/main/resources/META-INF/withKotlin.xml

Add K2 support

---

.github/workflows/main.yml
build.gradle
gradle.properties
src/main/java/org/mapstruct/intellij/codeinsight/references/MapstructMappingQualifiedByNameReference.java
src/main/java/org/mapstruct/intellij/util/SourceUtils.java
src/main/java/org/mapstruct/intellij/util/TargetUtils.java
src/main/resources/META-INF/plugin.xml
src/test/java/org/mapstruct/intellij/MapstructBaseCompletionTestCase.java
src/test/java/org/mapstruct/intellij/MapstructCompletionJdk17TestCase.java
src/test/java/org/mapstruct/intellij/inspection/JavaExpressionUnnecessaryWhitespacesInspectorTest.java
src/test/java/org/mapstruct/intellij/inspection/UnmappedRecordTargetPropertiesInspectionTest.java
src/test/java/org/mapstruct/intellij/inspection/UnmappedTargetPropertiesInspectionSourceBeforeTargetTest.java
src/test/java/org/mapstruct/intellij/inspection/UnmappedTargetPropertiesInspectionTest.java
src/test/java/org/mapstruct/intellij/rename/RenameHandlerJdk17Test.java
testData/inspection/UnmappedTargetProperties_after.java

Adjust minimum IntelliJ version and remove downloads of mockJDK

---

README.md
description.html
src/main/java/org/mapstruct/intellij/codeinsight/references/BaseReference.java
src/main/java/org/mapstruct/intellij/inspection/MapstructReferenceInspection.java
src/main/resources/META-INF/plugin.xml
src/main/resources/inspectionDescriptions/MapstructReferenceInspection.html
src/main/resources/org/mapstruct/intellij/messages/MapStructBundle.properties
src/test/java/org/mapstruct/intellij/inspection/MapstructReferenceInspectionTest.java
testData/inspection/UnknownIgnoreUnmappedSourceReference.java
testData/inspection/UnknownNestedSourceReference.java
testData/inspection/UnknownNestedTargetReference.java
testData/inspection/UnknownQualifiedByNameReferenceReference.java
testData/inspection/UnknownSourceReference.java
testData/inspection/UnknownTargetReference.java
testData/inspection/UnknownValueMappingSourceReference.java
testData/inspection/UnknownValueMappingTargetReference.java

I added an inspection which reports all unknown mapstruct references as unknown symbol errors. This also works for references with  dot notation.
My implemtation is based on [https://github.com/JetBrains/intellij-community/blob/master/plugins/IntelliLang/src/org/intellij/plugins/intelliLang/references/InjectedReferencesInspection.java](https://github.com/JetBrains/intellij-community/blob/master/plugins/IntelliLang/src/org/intellij/plugins/intelliLang/references/InjectedReferencesInspection.java).
I added tests for all mapstruct references:
- `source` in `@Mapping` annotation
- `target` in `@Mapping` annotation
- `source` in `@ValueMapping` annotation
- `target` in `@ValueMapping` annotation
- `qualifiedByName` in `@Mapping` annotation
For nested targets the inspection looks like
fixes …

add unknown reference inspection

---

change-notes.html
src/main/java/org/mapstruct/intellij/codeinsight/references/MapstructTargetReference.java
src/main/java/org/mapstruct/intellij/util/TargetUtils.java
src/test/java/org/mapstruct/intellij/MapstructCompletionTestCase.java
testData/inspection/UnmappedCollectionGetterPropertiesData.java
testData/mapping/TargetWithCollectionGetterMapper.java
testData/mapping/TargetWithMapGetterMapper.java

#217: Make sure that Collection / Map getter write accessors are properly resolved

---

src/main/java/org/mapstruct/intellij/codeinsight/references/BaseValueMappingReference.java
src/main/java/org/mapstruct/intellij/codeinsight/references/ValueMappingSourceReference.java
src/main/java/org/mapstruct/intellij/codeinsight/references/ValueMappingTargetReference.java
src/main/java/org/mapstruct/intellij/inspection/MapstructReferenceInspection.java
testData/inspection/UnknownValueMappingSourceReference.java
testData/inspection/UnknownValueMappingTargetReference.java

#218: Do not mark String source / target in ValueMapping as error

---

src/main/java/org/mapstruct/intellij/codeinsight/references/BaseMappingReference.java
src/main/java/org/mapstruct/intellij/codeinsight/references/BaseReference.java
src/main/java/org/mapstruct/intellij/codeinsight/references/BaseValueMappingReference.java
src/main/java/org/mapstruct/intellij/codeinsight/references/MapstructMappingQualifiedByNameReference.java
src/main/java/org/mapstruct/intellij/codeinsight/references/MapstructSourceReference.java
src/main/java/org/mapstruct/intellij/codeinsight/references/MapstructTargetReference.java
src/main/java/org/mapstruct/intellij/inspection/MapstructReferenceInspection.java
src/main/resources/org/mapstruct/intellij/messages/MapStructBundle.properties
testData/inspection/UnknownIgnoreUnmappedSourceReference.java
testData/inspection/UnknownNestedSourceReference.java
testData/inspection/UnknownNestedTargetReference.java
testData/inspection/UnknownQualifiedByNameReferenceReference.java
testData/inspection/UnknownSourceReference.java
testData/inspection/UnknownTargetReference.java
testData/inspection/UnknownValueMappingSourceReference.java
testData/inspection/UnknownValueMappingTargetReference.java

#223: Improve error messages for reference inspection

---

src/main/java/org/mapstruct/intellij/codeinsight/references/MapstructMappingQualifiedByNameReference.java
src/test/java/org/mapstruct/intellij/completion/MappingQualifiedByNameCompletionTestCase.java
testData/completion/qualifiedbyname/MappingQualifiedByNameWithAllPossibleVisibilities.java
testData/completion/qualifiedbyname/mapper/BaseMapper.java
testData/completion/qualifiedbyname/mapper/ExternalMapper.java
testData/completion/qualifiedbyname/mapper/SamePackageMapper.java

#226: Reference only accessible qualified methods

---

src/test/java/org/mapstruct/intellij/bugs/_235/EnumImplementingInterfaceTest.java
testData/bugs/_235/EnumImplementingInterface.java

#235: Add a regression test for an enum implementing an interface

---

src/main/java/org/mapstruct/intellij/inspection/MapstructReferenceInspection.java
src/test/java/org/mapstruct/intellij/bugs/_236/DisableSourceAndTargetPropertyInspectionOnAnnotationsTest.java
testData/bugs/_236/DisableSourceAndTargetPropertyInspectionOnAnnotations.java

closes #236 
I tried to disable it by excluding it in the `MapstructReferenceContributor` when using the [`elementPattern`](https://github.com/mapstruct/mapstruct-idea/blob/59026197610f7d27f12cdc122961d35e753206ae/src/main/java/org/mapstruct/intellij/util/MapstructElementUtils.java#L78)` but somehow this did not get called.
Therefore I used the check inside `shouldRegisterProblem(...)` to exclude it.

#236: Do not register problems on mapping composition annotations

---

src/main/java/org/mapstruct/intellij/inspection/TargetPropertyMappedMoreThanOnceInspection.java
testData/inspection/TargetPropertyMappedMoreThanOnce.java
testData/inspection/TargetPropertyMappedMoreThanOnce_after.java

#241 Target dot should not be treated as mapped more than once
